[en]
  title = "fage's Blog"
  languageName = "中文"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

#[en]
#  title = "Hugo Zzo Theme"
#  languageName = "English"
#  weight = 2
#  languagedir = "ltr"
#  contentdir = "content/en"
