[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 1

[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 2

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 3

#[[main]]
#  identifier = "presentation"
#  name = "Pt"
#  url = "presentation"
#  weight = 3

#[[main]]
#  identifier = "gallery"
#  name = "Gallery"
#  url = "gallery"
#  weight = 4
    
#[[main]]
#  parent = "gallery"
#  name = "Cartoon"
#  url = "gallery/cartoon"

#[[main]]
#  parent = "gallery"
#  name = "Photo"
#  url = "gallery/photo"

#[[main]]
#  identifier = "showcase"
#  name = "Showcase"
#  url = "showcase"
#  weight = 6

#[[main]]
#  identifier = "publication"
#  name = "Pub"
#  url = "publication"
#  weight = 7